# Configuração da URL para o H2 em modo arquivo
spring.datasource.url=jdbc:h2:mem:draence;DB_CLOSE_ON_EXIT=FALSE

# Nome de usuário e senha
spring.datasource.username=draence
spring.datasource.password=drae
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

